### ISSUE TITLE
Trying code to convert rule set into character string

### ISSUE THREAD

**Issue by harryrana2003** [janusza/RoughSets#4]
I want to convert rule sets into character string  (IF then format)
1. rules <- RI.CN2Rules.RST(d.tra, K = 5)
2. rules.rst <- RI.indiscernibilityBasedRules.RST(d.tra, red.rst)

how can i use your code to get desired results.

Thanks
# ' A function for converting a set of rules into their character representation.
# '
# ' @title The \code{as.character} method for RST rule sets
# ' @author Andrzej Janusz
# '
# ' @param x a \code{"RuleSetRST"} object. See \code{\link{RI.LEM2Rules.RST}}.
# ' @param ... the other parameters.
# ' @return Converts rules from a set into their character representation.
# ' @examples
# '
# ' ## Example : Converting a set of decision rules
# '
# ' data(RoughSetData)
# ' hiring.data <- RoughSetData$hiring.dt
# '
# ' rules <- RI.LEM2Rules.RST(hiring.data)
# '
# ' as.character(rules)
# ' @export
# ' @method as.character RuleSetRST

as.character.RuleSetRST = function(x, ...) {

  if(!inherits(x, "RuleSetRST")) stop("not a legitimate object in this package")
  colNames <- attr(x, "colnames")
  rules <- sapply(x, convertRuleIntoCharacter, colNames, decName = attr(x, "dec.attr"))
  rules <- sub('\n\t\t', ' ', rules)
  rules
}
# auxiliary function used in print and as.character methods of RuleSetRST objects

convertRuleIntoCharacter = function(x, colNames, decName) {
  desc <- paste(colNames[x$idx[1]], x$values[1], sep = " is ")
  if(length(x$values) > 1) {
    for (j in 2 : length(x$values)){
      temp <- paste(colNames[x$idx[j]], x$values[j], sep = " is ")
      desc <- paste(desc, temp, sep = " and ")
    }
  }
  cons <- paste(decName, paste(x$consequent, ";\n\t\t(supportSize=",
                               length(x$support), "; ", "laplace=",
                               x$laplace,")", sep=""), sep = c(" is "))
  rule <- paste("IF", desc, "THEN", cons)
  rule
}

**Comment by janusza** [comment]
Hello!

Typically, you just need to use the 'as.character' method. In your case you may try:

rules.chr <- as.character(rules)

Please, write if it solves your problem.

Andrzej

**Comment by janusza** [comment]
Since you do not respond, I'm assuming that everything works for you and I'm closing the issue.

Best regards,
Andrzej
